### ISSUE TITLE
Script spits out error about windows resource protection failure

### ISSUE THREAD

**Issue by o0Eidolon0o** [PC-Help-Hub/pchh-main#10]
![image](https://github.com/user-attachments/assets/b65191ff-6ca6-4176-8062-582fd6bc884a)

**Comment by shinthebean1** [comment]
There isn't any reading output in the script for SFC, that's just your Windows.

**Comment by o0Eidolon0o** [comment]
So what is the user supposed to do in this case? Perhaps it would be good to add a writeout for this specific case or something

**Comment by shinthebean1** [comment]
> So what is the user supposed to do in this case? Perhaps it would be good to add a writeout for this specific case or something

I can't find a way to properly filter the output of sfc without creating another file, and same thing with creating a file. That's why I gave up on that and make it just spit out the normal output of sfc

**Comment by o0Eidolon0o** [comment]
Why is logfile creation an issue to begin with?

**Comment by shinthebean1** [comment]
> Why is logfile creation an issue to begin with?

I'm saying I can't find a method to read the output of sfc and redirect the script.

**Comment by o0Eidolon0o** [comment]
That is not an answer to my question.
That aside, you can still put output of commands into variables in batch

**Comment by shinthebean1** [comment]
> That is not an answer to my question. That aside, you can still put output of commands into variables in batch

I tried doing it in batch for a week straight, with powershell and without. I cannot get it to work. that's what made me make this in powershell, also sly's request.

**Comment by shinthebean1** [comment]
> > That is not an answer to my question. That aside, you can still put output of commands into variables in batch
> 
> I tried doing it in batch for a week straight, with powershell and without. I cannot get it to work. that's what made me make this in powershell, also sly's request.

I've tried using exit codes, saving to an output, using fuckin logic, elseif statements, if statements, text files, etc. I would use findstr except the character limit stops me.

**Comment by shinthebean1** [comment]
No need to change the direction of the script by sfc /scannow's output. It's self-explanatory (if it says restart for changes to apply, then they will restart the PC, and they just use common sense)

There's nothing in the script that will cause "cannot perform the requested operation" as the script literally only has "sfc /scannow" and that's it.

**Comment by o0Eidolon0o** [comment]
> There's nothing in the script that will cause "cannot perform the requested operation" as the script 

Yes, but that doesn't mean it won't happen. The user should, in my opinion, be told what's happening. Pretty sure there should be an error level for this thing.

**Comment by shinthebean1** [comment]
> > There's nothing in the script that will cause "cannot perform the requested operation" as the script
> 
> Yes, but that doesn't mean it won't happen. The user should, in my opinion, be told what's happening. Pretty sure there should be an error level for this thing.

Sorry I don't rlly understand what you mean? There's zero reason to redirect the script as it'll say the exact same output except without a progress bar and the extra shit sfc does.

**Comment by o0Eidolon0o** [comment]
Imagine you are a BFU who has 0 clue what is happening in this script. You attempt to run this but get the output above. You will be left with nothing but questions.
Hencewhy I think there should be a message about this being an external issue.

**Comment by shinthebean1** [comment]
> Imagine you are a BFU who has 0 clue what is happening in this script. You attempt to run this but get the output above. You will be left with nothing but questions. Hencewhy I think there should be a message about this being an external issue.

You can try to add code to get the script redirected correct for when it says "reboot/restart", "corrupt files found and successfully repaired them", "no corrupt files found", etc. I've tried all the things I can think of, I want to try it without the need of creating a file.

**Comment by o0Eidolon0o** [comment]
You talk about text outputs while ignoring what I mentioned - error levels. There is no reason for all this language BS when numbers are always the same

**Comment by shinthebean1** [comment]
> You talk about text outputs while ignoring what I mentioned - error levels. There is no reason for all this language BS when numbers are always the same

so there's different error levels for every single output of sfc?

**Comment by o0Eidolon0o** [comment]
I believe there should be, yes, although it's not something I checked given I don't particularly have corrupted windows at hand. There should certainly be an OK exit code and at least one error exit code

**Comment by shinthebean1** [comment]
I looked thru sfc documentation, there isn't specific exit codes for specific outputs of SFC.

**Comment by shinthebean1** [comment]
> I believe there should be, yes, although it's not something I checked given I don't particularly have corrupted windows at hand. There should certainly be an OK exit code and at least one error exit code

You can test it in a VM by deleting random windows files (in my case i just delete a few at the bottom of the windows folder) though you need permission from trusted installer which takes like 10 seconds to do

**Comment by o0Eidolon0o** [comment]
Actually why not just use an `else`?

**Comment by shinthebean1** [comment]
i did, i've tried everything to read the output.

**Comment by o0Eidolon0o** [comment]
> i did, i've tried everything to read the output.

 The log path is the same 100 % of the time and as far as I am aware that is always present if the repair operation fails both with SFC and DISM.

**Comment by shinthebean1** [comment]
Will look into filtering the output of sfc later..

**Comment by shinthebean1** [comment]
Correctly filters out script now | https://github.com/PC-Help-Hub/pchh-main/commit/3423cac097584226df63c3cd4ae5da9beb485513
