### ISSUE TITLE
%zip_tar% cannot be set properly if a different than english locale is used

### ISSUE THREAD

**Issue by o0Eidolon0o** [PC-Help-Hub/pchh-main#6]
If Desktop is not called Desktop such as due to a different locale being used, %zip_tar% will not be found and the powershell operation will fail

**Comment by o0Eidolon0o** [comment]
Will attempt to replace the desktop if with a path to Desktop environment variable

**Comment by shinthebean1** [comment]
> If Desktop is not called Desktop such as due to a different locale being used, %zip_tar% will not be found and the powershell operation will fail

So if desktop isnt called desktop or is in a different language, it will fail?

**Comment by o0Eidolon0o** [comment]
That's my guess at least, I don't think I have been able to reproduce this error yet. Will keep trying.

**Comment by o0Eidolon0o** [comment]
Issue was indeed the different name for Desktop. The powershell environtment variable for desktop was set properly, but the name just didn't match. Was unable to reproduce the issue, however a fix has still been successfully implemented
