### ISSUE TITLE
Language Problem with image.ps1

### ISSUE THREAD

**Issue by shinthebean1** [PC-Help-Hub/pchh-main#7]
If system language is anything other than English, the script will throw an error for the DISM commands;

**Comment by shinthebean1** [comment]
I'm thinking either we add the same text but for the top languages, and whoever gets the error i'll just grab their output and translate it and put it in.

Or we can use something external to translate.

**Comment by o0Eidolon0o** [comment]
Consider not pursuing this line at all. Powershell has one advantage that you have not taken advantage of which is built in logging, perhaps look into that.

**Comment by shinthebean1** [comment]
> Consider not pursuing this line at all. Powershell has one advantage that you have not taken advantage of which is built in logging, perhaps look into that.

Can you link the documentation for that?

**Comment by o0Eidolon0o** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript
Surely you are aware of the learn documentation

**Comment by shinthebean1** [comment]
> https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript Surely you are aware of the learn documentation

I am..
But how will start-transcript translate the messages for all supported languages..? that's the issue.

**Comment by o0Eidolon0o** [comment]
Why would it? It's less work translating it yourself as needed than including XYZ variations due to languages

**Comment by shinthebean1** [comment]
> Why would it? It's less work translating it yourself as needed than including XYZ variations due to languages

is there another thing i can do that makes the powershell session to english? I can't see how start-transcript makes all other languages work with the script as the script's looking for an english output

**Comment by o0Eidolon0o** [comment]
> is there another thing i can do that makes the powershell session to english? I can't see how start-transcript makes all other languages work with the script as the script's looking for an english output

Google is your friend.

**Comment by shinthebean1** [comment]
Witthin a few days I will add this so it can work for all languages.

**Comment by o0Eidolon0o** [comment]
Okay but why do you need to make decisions based on the command output when you are subsequently throwing it away anyway? Might as well just change the language to english and pipe out the command output to stdout

**Comment by shinthebean1** [comment]
I'm talking about for the scan outputs bc that's needed to get the script time efficient

**Comment by o0Eidolon0o** [comment]
What?

**Comment by shinthebean1** [comment]
> What?

I only need to change the output for the /scanhealth and the /checkhealth, it's been like this for a few weeks my guy

**Comment by shinthebean1** [comment]
![image](https://github.com/user-attachments/assets/df560c9f-f27e-42d4-b9d3-dccfc9e2bd96)

**Comment by o0Eidolon0o** [comment]
okay, two things:
A) Why not use the part of the command writeout that is always the same if the fix operation fails?
B) Why even bother when you can just pipe out the results of the command to stdout to the same effect?

**Comment by shinthebean1** [comment]
> okay, two things: A) Why not use the part of the command writeout that is always the same if the fix operation fails? B) Why even bother when you can just pipe out the results of the command to stdout to the same effect?

im not sure what you mean, plus isnt stdout linux

**Comment by shinthebean1** [comment]
but it works exactly the same way? it outputs like it should. I see no issue with this part of the script.

**Comment by o0Eidolon0o** [comment]
> but it works exactly the same way? it outputs like it should. I see no issue with this part of the script.

You are trying to add output based on things that are already implemented. Adding your own writeouts depending on the command output is senseless when the commands themselves already have an easily readable and understandeable output as well as progress reporthing, which your solution lacks.

**Comment by shinthebean1** [comment]
> > but it works exactly the same way? it outputs like it should. I see no issue with this part of the script.
> 
> You are trying to add output based on things that are already implemented. Adding your own writeouts depending on the command output is senseless when the commands themselves already have an easily readable and understandeable output as well as progress reporthing, which your solution lacks.

looks nice, plus this is quite literally what you are trying to achieve with sfc..

**Comment by o0Eidolon0o** [comment]
> looks nice

It is less functional and informative than the default output.

**Comment by shinthebean1** [comment]
it says the same output while cutting out 90% of the normal output

**Comment by o0Eidolon0o** [comment]
> it says the same output while cutting out 90% of the normal output

It cuts like 3 or 4 lines, that's nothing groundbreaking. And cutting it out for what reason? It ommits the progress reporting which is definitely a nice to have so people don't just sit and stare at the screen and limits you to english only given you would have to change the system language for the output to differ.

**Comment by shinthebean1** [comment]
> > it says the same output while cutting out 90% of the normal output
> 
> It cuts like 3 or 4 lines, that's nothing groundbreaking. And cutting it out for what reason? It ommits the progress reporting which is definitely a nice to have so people don't just sit and stare at the screen and limits you to english only given you would have to change the system language for the output to differ.

so what do you want me to do to have it still redirect the output without having language get in the way.

**Comment by o0Eidolon0o** [comment]
At the very least just have the commands output directly to the command line, yes. This whole exercise makes no sense.

**Comment by shinthebean1** [comment]
> At the very least just have the commands output directly to the command line, yes. This whole exercise makes no sense.

so what you want me to remove the time efficient shit i added in there which is change the output of the script depending on on the output of scanhealth/checkhealth? It saves like 15 minutes. Both run SFC

**Comment by shinthebean1** [comment]
i genuinely see no problem, you're saying to remove things that don't need to be removed..

sly said "I think powershell is easier, more powrful", "I use powershell scripts every day at work and people can launch it with one command"

Powershell: paste a command, script starts no issues.
Batch: Download it, have to select "keep file", then "keep anyway"; Then run the file, have windows have like 2 checkpoints and then it lets you install it.

This is why we need to just stop using batch, use powershell instead. It is 10 times faster.

The script I have made with image.ps1 only has the one issue which is language. I can fix this, I will look into it.

Removing all this that is meant to just make it look like is useless, it just makes it ugly.

Nobody that has ran this script has ever complained of horrible or bad functionality. It performs exactly as I want it, if a user has an issue with the script I will dedicate my time to fixing it, it kinda sucks when you wanna like remove the things i purposely added to make it user-friendly and time efficient n shit

You're the only one in the server that has complained about it, it functions just as i want it.

**Comment by shinthebean1** [comment]
I created this issue to address an issue where it would throw the error if the system language isnt english. You should be like sending possible solutions instead of trying to remove thing that i personally and purposely added, the issue went completely off topic for no reason

**Comment by o0Eidolon0o** [comment]
Removing useless pieces of script is a valid solution to a problem that has no reason to exist to begin with.

**Comment by shinthebean1** [comment]
Will look into a solution for the language issue soon.

**Comment by shinthebean1** [comment]
SFC is done, referred to exit codes; Will try using DISM

**Comment by shinthebean1** [comment]
https://github.com/PC-Help-Hub/pchh-main/commit/3423cac097584226df63c3cd4ae5da9beb485513 Fixed.
