### ISSUE TITLE
image.ps1 doesn't load due to the IExplorer engine being unavailable

### ISSUE THREAD

**Issue by o0Eidolon0o** [PC-Help-Hub/pchh-main#8]
![image](https://github.com/user-attachments/assets/098b2aad-26f2-401d-a537-3b4a4b0f87d6)

**Comment by shinthebean1** [comment]
Try adding the -UseBasicParsing parameter to the iwr, see if the script below works (powershell has to be ran as admin for it to work correctly)

[image script.zip](https://github.com/user-attachments/files/16200953/image.script.zip)

**Comment by o0Eidolon0o** [comment]
that is indeed the solution
