### ISSUE TITLE
Cannot run image.ps1 from the file directly

### ISSUE THREAD

**Issue by o0Eidolon0o** [PC-Help-Hub/pchh-main#9]
The image.ps1 cannot be ran directly from a downloaded file. I find this problematic given how often users mess up or straight up ignore instructions

**Comment by shinthebean1** [comment]
There's no self-elevation because it broke out of no where, no other method i found online to self-elevate works. That's why it doesn't work while downloaded.

To run it while downloaded, you have to open powershell as an admin, CD to the directory it's installed at, and do .\image.ps1

**Comment by shinthebean1** [comment]
And also it's more complicated to manually run the file than running the iex powershell line

**Comment by shinthebean1** [comment]
you COULD try self-elevation with
``` if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Host "Prompting UAC.."
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}```

Try it in a VM because it kinda works, dunno how to explain it.

**Comment by o0Eidolon0o** [comment]
> To run it while downloaded, you have to open powershell as an admin, CD to the directory it's installed at, and do. \image.ps1

This is not a viable method, does not take care of execution policy, which is outside of Linux KVMs set to restricted by default. While I agree the command is simpler and faster, I imagine there is a sleugh of users who would rather do it the dumb GUI way than pasting commands, or at least just blindly download the file without reading the description. I therefore think it would be better if the script was capable to circumvent these one way or another.

**Comment by shinthebean1** [comment]
> > To run it while downloaded, you have to open powershell as an admin, CD to the directory it's installed at, and do. \image.ps1
> 
> This is not a viable method, does not take care of execution policy, which is outside of Linux KVMs set to restricted by default. While I agree the command is simpler and faster, I imagine there is a sleugh of users who would rather do it the dumb GUI way than pasting commands, or at least just blindly download the file without reading the description. I therefore think it would be better if the script was capable to circumvent these one way or another.

Well I don't know how to do that. Though the script already bypasses the execution policy at the first line. You can't manually run the file thru file explorer without having an unrestricted execution policy.

**Comment by o0Eidolon0o** [comment]
First of all, I am questioning why this has been moved to powershell when there are basically no advantages to it as far as I can tell. There isn't really anything new in the script but yet it's bloated to all hell

**Comment by o0Eidolon0o** [comment]
> Well I don't know how to do that. Though the script already bypasses the execution policy at the first line. You can't manually run the file thru file explorer without having an unrestricted execution policy.

No you cannot, the first line there does nothing since you can't run the script to begin with unless your execpol is already in a positive state, so the line never gets executed or doesn't need to be executed.

**Comment by shinthebean1** [comment]
> > Well I don't know how to do that. Though the script already bypasses the execution policy at the first line. You can't manually run the file thru file explorer without having an unrestricted execution policy.
> 
> No you cannot, the first line there does nothing since you can't run the script to begin with unless your execpol is already in a positive state, so the line never gets executed or doesn't need to be executed.

I've tested it. If the script is being ran as intended, thru iex in powershell terminal, it will correctly run the first line. you just need the unrestricted execution policy if running the file with file explorer.

**Comment by shinthebean1** [comment]
> > Well I don't know how to do that. Though the script already bypasses the execution policy at the first line. You can't manually run the file thru file explorer without having an unrestricted execution policy.
> 
> No you cannot, the first line there does nothing since you can't run the script to begin with unless your execpol is already in a positive state, so the line never gets executed or doesn't need to be executed.

I changed it to powershell because of AV's, sly's request, and being able to expand my knowledge & also having more "power" if that makes sense. Like I can do a lot more.

**Comment by o0Eidolon0o** [comment]
> I changed it to powershell because of AV's

Elaborate. How exactly is batch different from that point of view?
> having more "power" if that makes sense. Like I can do a lot more.

The script doesn't, and doesn't even need to, take advantage of any of the 'power' though, it does the exact same thing as the batch one except it's multiple times the size.

**Comment by shinthebean1** [comment]
> > I changed it to powershell because of AV's
> 
> Elaborate. How exactly is batch different from that point of view?
> 
> > having more "power" if that makes sense. Like I can do a lot more.
> 
> The script doesn't, and doesn't even need to, take advantage of any of the 'power' though, it does the exact same thing as the batch one except it's multiple times the size.

As I said, AV's go crazy because it's a batch file. Sly asked me to make it into powershell, mostly because batch has issues with trying to use powershell correctly with the entire script; The script is 99% functional except a few issues which are the other 2 threads. The size doesn't really matter it flows properly and exactly how i want it.

**Comment by o0Eidolon0o** [comment]
> As I said, AV's go crazy because it's a batch file. 

I have yet to see any proof of that
> The script is 99% functional except a few issues which are the other 2 threads.

It is functional in the same manner, but that is exactly my point - why do we _need_ powershell again? Like I mentioned before, it's not like it's actually doing anything batch can't.
> The size doesn't really matter it flows properly and exactly how i want it.

It is convoluted, orientation in it is difficult for users and some of the decisions make 0 sense.

**Comment by shinthebean1** [comment]
wdym some decisions make 0 sense? it redirects how I want it and It works exactly as i wanted it to work. I've made it as user friendly as possible.

**Comment by shinthebean1** [comment]
> > As I said, AV's go crazy because it's a batch file.
> 
> I have yet to see any proof of that
> 
> > The script is 99% functional except a few issues which are the other 2 threads.
> 
> It is functional in the same manner, but that is exactly my point - why do we _need_ powershell again? Like I mentioned before, it's not like it's actually doing anything batch can't.
> 
> > The size doesn't really matter it flows properly and exactly how i want it.
> 
> It is convoluted, orientation in it is difficult for users and some of the decisions make 0 sense.

Avast, Malwarebytes, and other AV's have ended up blocking the batch file simply because it's batch and it's doing DISM and SFC. But it doesn't do it with powershell.

**Comment by shinthebean1** [comment]
> First of all, I am questioning why this has been moved to powershell when there are basically no advantages to it as far as I can tell. There isn't really anything new in the script but yet it's bloated to all hell

and if you want to try to debloat it, be my guest. But do a pull request so we can decide what to do b4 posting the final thing

**Comment by o0Eidolon0o** [comment]
> Avast, Malwarebytes, and other AV's have ended up blocking the batch file simply because it's batch and it's doing DISM and SFC. But it doesn't do it with powershell.

Have you actually tested it? I have (avast, eset premium, malwarebytes premium, and BD free) and none of the old scripts get caught, there is no reason to begin with.

**Comment by shinthebean1** [comment]
> > Avast, Malwarebytes, and other AV's have ended up blocking the batch file simply because it's batch and it's doing DISM and SFC. But it doesn't do it with powershell.
> 
> Have you actually tested it? I have (avast, eset premium, malwarebytes premium, and BD free) and none of the old scripts get caught, there is no reason to begin with.

I saw it on people trying to use the script.. But anyway sly still recommended me using powershell.

**Comment by o0Eidolon0o** [comment]
Yes because you trying to use powershell from CMD was a bit of a mess as far as I could see. However there is no reason to use powershell at all as I have explained.

**Comment by shinthebean1** [comment]
> Yes because you trying to use powershell from CMD was a bit of a mess as far as I could see. However there is no reason to use powershell at all as I have explained.

Well it's already done and it has the same functionality if not better.

**Comment by o0Eidolon0o** [comment]
What additional functionality does it have besides coloured text which you can also do in cmd?

**Comment by shinthebean1** [comment]
> What additional functionality does it have besides coloured text which you can also do in cmd?

there aint no point in arguing abt it bc it's already done. Exact same functionality. I learned a new language, i aint see nothing wrong other than bypassing some AV's blocking it

**Comment by o0Eidolon0o** [comment]
> there aint no point in arguing abt it bc it's already done.

Reverting to any of the older versions isn't hard, which is what I suggest be done for the sake of simplicity and cleanliness. We can even keep the command launch guide for people who prefer that. 
Again the AV thing is a non-issue as the script is doing nothing even remotely suspicious.

**Comment by shinthebean1** [comment]
There's no point in keeping both scripts, it'll just over complicate things. There is zero reason to keep both, only one is needed. I put a shit ton of time into learning powershell and i wanna put it to use. Why don't we just keep powershell as it has the exact same functionality. I'm not working on the .bat anymore tho

**Comment by o0Eidolon0o** [comment]
I am not suggesting that. I am suggesting moving to the older one. 
We can create an in-progress folder in the repository when projects such as this one can be cultivated until they are ready/reasonable to be added to the main part of the repo

**Comment by shinthebean1** [comment]
there's no reason to switch back to the older one, the batch one gets detected by an AV, the powershell one doesn't. It's easier to just put in one command into powershell and having the entire script work rather than downloading a random file, running it, having windows block it bc it isn't signed, etc. It's functionally easier to keep the powershell script.

**Comment by shinthebean1** [comment]
Let's wait for sly on this one.

**Comment by o0Eidolon0o** [comment]
> the batch one gets detected by an AV

Untrue. Tested + common sense.
> It's easier to just put in one command into powershell and having the entire script work rather than downloading a random 

It's even better to have both options. You also get the bonus of autoelevation being easy for you.

**Comment by shinthebean1** [comment]
> > the batch one gets detected by an AV
> 
> Untrue. Tested + common sense.
> 
> > It's easier to just put in one command into powershell and having the entire script work rather than downloading a random
> 
> It's even better to have both options. You also get the bonus of autoelevation being easy for you.

It is a lot slower to do the batch file, bc you have to download it, run it, accept UAC, and click 3 more things to even start the script. It's just copy and paste with the powershell one. If we keep both then we have to maintain both to make sure there's absolutely no errors with either of them

**Comment by shinthebean1** [comment]
> > > the batch one gets detected by an AV
> > 
> > 
> > Untrue. Tested + common sense.
> > > It's easier to just put in one command into powershell and having the entire script work rather than downloading a random
> > 
> > 
> > It's even better to have both options. You also get the bonus of autoelevation being easy for you.
> 
> It is a lot slower to do the batch file, bc you have to download it, run it, accept UAC, and click 3 more things to even start the script. It's just copy and paste with the powershell one. If we keep both then we have to maintain both to make sure there's absolutely no errors with either of them

I have quite literally seen AV's delete the batch file and mark it as malware.

**Comment by o0Eidolon0o** [comment]
I have never had issues with any legitimate batch files I've made, nor the original version of this, nor the version I personally made ages ago.
And again, I even retested it about 1-2 hours ago just to check, even enabled some additional protection settings in MWB and Eset.
And let me reiterate:
**It's even better to have both options. I personally agree with the command being simpler, but some users just prefer the GUI method of doing this. I also proposed that we should keep both.**

**Comment by shinthebean1** [comment]
> I have never had issues with any legitimate batch files I've made, nor the original version of this, nor the version I personally made ages ago.

I don't know what to tell you. I've watched people via screenshare run the batch file, some AV's flag it as malware and it gets deleted. Let's either just keep the powershell script for time saving and functionality, or just wait for Sly to decide. It's overcomplicating things to keep both scripts.

**Comment by shinthebean1** [comment]
I just really do not see a reason to keep the batch script when we have a faster powershell script.

**Comment by o0Eidolon0o** [comment]
How exactly would it be faster than using batch + command? It's not like you can't just download it through curl and launch it in cmd

**Comment by shinthebean1** [comment]
> How exactly would it be faster than using batch + command? It's not like you can't just download it through curl and launch it in cmd

i really don't know why you only want to do batch. Batch is slower to run, powershell is more reliable end of story.. there's absolutely ZERO issue with the script other than the language thing which i will fix.

**Comment by shinthebean1** [comment]
https://github.com/PC-Help-Hub/pchh-main/issues/7#issuecomment-2226902628 read this

**Comment by o0Eidolon0o** [comment]
> Batch is slower to run
 
 False.
  > powershell is more reliable 
 
 Irrelevant point in this case
 > there's absolutely ZERO issue with the script other than the language thing which i will fix.
 
 Except for it being bloated and using PoSH for no reason since you take advantage of 0 of its features while also trying to fix a non-issue of the writeouts and failing due to the languages.

**Comment by o0Eidolon0o** [comment]
> [#7 (comment)](https://github.com/PC-Help-Hub/pchh-main/issues/7#issuecomment-2226902628) read this

Funny that you act as if  I didn't read it while also ignoring what I said. The same command execution is available in batch while also

- retaining simple autoelevation
- cleaner script
- retaining the file in case of reuse
- giving users the option to download and run it manually if they so choose

**Comment by shinthebean1** [comment]
```    Write-Host "Prompting UAC.."
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}```

here's the self elevation, works the same way.

No need to retain the file, all the info you need is in the script.

If the user wants to run it, they can just download the script and google "how to run powershell scripts"

**Comment by o0Eidolon0o** [comment]
> If the user wants to run it, they can just download the script and google "how to run powershell scripts"

Yeah very simple unlike double clicking the file 
> No need to retain the file, all the info you need is in the script.

the script that.. gets iwr iex and it's gone?

**Comment by shinthebean1** [comment]
> Yeah very simple unlike double clicking the file

you did not read what i said.

It's not just "double click the file". Windows actively blocks the download as well as trying to block you running it.

Powershell is 100% faster and easier, if they ever want to download it; a quick google search and a brain will get you in the right path.

**Comment by shinthebean1** [comment]
iwr iex is simple, easy to run, doesnt download it. It can be downloaded and ran easier than batch anyway

**Comment by o0Eidolon0o** [comment]
> iwr iex is simple, easy to run, doesnt download it. It can be downloaded and ran easier than batch anyway

Could you stop ignoring the fact that batch can do the same exact thing while also giving you the file that you can use later. It fetches the contents off an HTTPS link supplied, for the purpouses of this thing the same exact way as curl does.

**Comment by shinthebean1** [comment]
> > iwr iex is simple, easy to run, doesnt download it. It can be downloaded and ran easier than batch anyway
> 
> Could you stop ignoring the fact that batch can do the same exact thing while also giving you the file that you can use later. It fetches the contents off an HTTPS link supplied, for the purpouses of this thing the same exact way as curl does.

if they need to do it again, copy paste a command in powershell. simple.

curl downloading a script then auto launching it can set off AV's (sly has said this)

**Comment by shinthebean1** [comment]
I'm completely against the idea of just deleting the perfectly fine and functional script for batch.
I'm waiting for @slydelv to respond, till then I'm done arguing. I vote to keep powershell, nothing's wrong with the script.

**Comment by o0Eidolon0o** [comment]
> if they need to do it again, copy paste a command in powershell. simple.

_Which is totally simpler than just running a locally stored file_
> curl downloading a script then auto launching it can set off AV's (sly has said this)

Doing that from a batch file can. Doing so from CMD directly does not.

**Comment by shinthebean1** [comment]
> > if they need to do it again, copy paste a command in powershell. simple.
> 
> _Which is totally simpler than just running a locally stored file_
> 
> > curl downloading a script then auto launching it can set off AV's (sly has said this)
> 
> Doing that from a batch file can. Doing so from CMD directly does not.

*it's totally more simple to having to click 5 times the amount of shit than pressing two keys to start a script*

**Comment by o0Eidolon0o** [comment]
> it's totally more simple to having to click 5 times the amount of shit than pressing two keys to start a script

Having to open browser, find the repo, navigate to the correct directory, copy the command, open windows search, locate powershell, run it as admin and copy paste it is easier than opening file explorer?

**Comment by shinthebean1** [comment]
> > it's totally more simple to having to click 5 times the amount of shit than pressing two keys to start a script
> 
> Having to find the repo, navigate to the correct directory, copy the command, open windows search, locate powershell, run it as powershell and copy paste it is easier than opening file explorer?

jst go to the discord and do !sfrep, it quite literally has the link in there. keep in mind this repo is for the discord

**Comment by shinthebean1** [comment]
![image](https://github.com/user-attachments/assets/6d613761-a4ec-45eb-b2a4-a9de51491c53)

**Comment by o0Eidolon0o** [comment]
Open browser/discord. Wait for either to load since discord likes to load up for a bit. Find the server among the joined server list. Go to the server and select a channel. Send the command. Copy the command output. Open powershell as administrator. Paste  the command.
vs 
Open file explorer. Double click.

**Comment by shinthebean1** [comment]
> Open browser/discord. Wait for either to load since discord likes to load up for a bit. Find the server among the joined server list. Go to the server and select a channel. Copy the command. Open powershell as administrator. Paste the command. vs Open file explorer. Double click.

the script is made **FOR** the **discord**. People only have the script to repair the system files, if they want to keep the file they can just download it and google how to do it.

You have the mindset that someone will genuinely run the script without the server asking them to. Nobody will do it, not one person that has ran or downloaded the script has asked to keep it. If they ask to keep it, i guide them on how to

**Comment by shinthebean1** [comment]
nobody will actually run this script out of their own time without being asked to by the discord, which is what the script was made for.,

**Comment by shinthebean1** [comment]
> Open browser/discord. Wait for either to load since discord likes to load up for a bit. Find the server among the joined server list. Go to the server and select a channel. Send the command. Copy the command output. Open powershell as administrator. Paste the command. vs Open file explorer. Double click.

orr you can just download the powershell script and click two buttons to open it

**Comment by o0Eidolon0o** [comment]
> nobody will actually run this script out of their own time without being asked to by the discord, which is what the script was made for.

That is an assumption with 0 backing. Back in my earlier times, I've seen plenty people reuse my scripts.

**Comment by o0Eidolon0o** [comment]
> orr you can just download the powershell script and click two buttons to open it

At this point you must be trolling, there is no way you do not understand that those steps preceed acquiring the powershell command needed to download the script.
The script by itself also will not run due to the default execution policy, I would've hoped you understood that at this point.

**Comment by shinthebean1** [comment]
> > orr you can just download the powershell script and click two buttons to open it
> 
> At this point you must be trolling, there is no way you do not understand that those steps preceed acquiring the powershell command needed to download the script.

I'm assuming they have a brain and have googling skills. I'm not removing the powershell script bc i took the time to make it functional and it works great and it's easy to use. I know the extent you have to go to run a powershell script due to execution policy, but that can be solved with **a google search**

**Comment by o0Eidolon0o** [comment]
Yeah and we both know people nowadays are SOOO skilled and willing with google, definitely not like 75 % of the issues in the server could be solved just by googling. Keep lying to yourself if you want to I suppose.

**Comment by shinthebean1** [comment]
> Yeah and we both know people nowadays are SOOO skilled with google. Keep lying to yourself if you want to I suppose.

either way, the script is FOR the server, not for ppl's sake. it's not intended to just be used whenever tf you want. It's meant to be ran when asked to, not like a fucking program.

**Comment by o0Eidolon0o** [comment]
> either way, the script is FOR the server, not for ppl's sake. it's not intended to just be used whenever tf you want. It's meant to be ran when asked to, not like a fucking program.

You cannot force users to only run it when YOU can reap their thanks for it. This should be generally helpful and not just for you to boost your ego.

**Comment by shinthebean1** [comment]
If they have an 

> > either way, the script is FOR the server, not for ppl's sake. it's not intended to just be used whenever tf you want. It's meant to be ran when asked to, not like a fucking program.
> 
> You cannot force users to only run it when YOU can reap their thanks for it. This should be generally helpful and not just for you to boost your ego.

dabbed been asking for you

here's what i think we should do

Keep the powershell script, lets not remove all that shit.
Make a new batch script without the powershell shit, just do the 4 dism commands and that's the entire script, so it can be easily downloaded, but the more advanced one is the powershell.

**Comment by shinthebean1** [comment]
So batch: simple asf
powershell: the full script that's time efficient and all that so batch doesnt give any sort of issues

**Comment by o0Eidolon0o** [comment]
> dabbed been asking for you

Off-topic. 
> Keep the powershell script, lets not remove all that shit.
Make a new batch script without the powershell shit, just do the 4 dism commands and that's the entire script, so it can be easily downloaded, but the more advanced one is the powershell.

I already said what I think should be done and stand behind that. This would be yet another exercise in pointlessness. It would be less user friendly, more difficult to run and more difficult to work with.

**Comment by shinthebean1** [comment]
so you're going against your own idea which is to make two scripts..

I'm saying to just make the downloaded batch script with dism commands, powershell script with the full thing

**Comment by shinthebean1** [comment]
so we both get what we want.
you get the batch script which is only for downloading and future use for if someone wants to use it
i get the powershell script which is for the server and has full functionality.

**Comment by o0Eidolon0o** [comment]
> so you're going against your own idea which is to make two scripts..

Kindly do not try to spin this against me. I am including what I said again in case you needed to refresh your memory on what I said.
> I am suggesting moving to the older one. _(refering to the batch file, for clarity)_
We can create an in-progress folder in the repository when projects such as this one _(refering to the powershell variant)_ can be cultivated until they are ready/reasonable to be added to the main part of the repo

**Comment by shinthebean1** [comment]
i disagree.

I want to get a very simple downloadable batch script. | has dism & sfc
I want to get the full powershell version for the server, which is what it's made for | server use, time efficient, full functionality, easy to read/manage, etc.

we get the best of both worlds.

**Comment by o0Eidolon0o** [comment]
>  server use, time efficient, full functionality, easy to read/manage, etc.

Okay for the last time - what functionality are we losing with batch exactly? Coloured text?

**Comment by shinthebean1** [comment]
> > server use, time efficient, full functionality, easy to read/manage, etc.
> 
> Okay for the last time - what functionality are we losing with batch exactly? Coloured text?

by that i mean the if statements to redirect the script based on the scan, internet check, etc.

**Comment by shinthebean1** [comment]
so the downloadable batch would be just a plain version of the powershell script. just dism and sfc.

**Comment by o0Eidolon0o** [comment]
> by that i mean the if statements to redirect the script based on the scan, internet check, etc.

1) if statements work in batch
2) internet connection checking works, and better I might add, in batch
What am I missing?

**Comment by shinthebean1** [comment]
ik they do. Why don't you make the batch file, just smth simple or something, just to make it work but downloadable, I keep my script.

**Comment by shinthebean1** [comment]
so you do whatever you want with the downloadable script, powershell script is for the server

**Comment by o0Eidolon0o** [comment]
The script was in the repo, happy hunting through the commit history!

**Comment by shinthebean1** [comment]
ill make the batch file i'll just only add the simple shit. I will do the dism & sfc cmds, and the internet check, and I'll tell sly to add the download link to the !sfrep command. Happy now?

**Comment by o0Eidolon0o** [comment]
I already said multiple times what I think should be done. There is no reason for me to change that at the moment.

**Comment by shinthebean1** [comment]
I'll do what you said and I'll add the finished script here, no hard feelings.

**Comment by shinthebean1** [comment]
[image.zip](https://github.com/user-attachments/files/16202789/image.zip)
this good?

**Comment by o0Eidolon0o** [comment]
Once again, I think I said what I believe to be the best course of action. I will not be responding to such comments anymore.
